### ISSUE TITLE
Change font family of the application

### ISSUE THREAD

**Issue by aquibbaig** [zairza-cetb/literature#129]
The font that we use in the game screen right now is not consistent across all the screens and cannot seem to distinguish "l" (jkl) , "I" (GHI) and 1 (one) properly given a roomId. Need to select a better solution for the font family.

**Comment by StrangeNoob** [comment]
@aquibbaig I think [Montserrat Alternate](https://fonts.google.com/specimen/Montserrat+Alternates?query=Il&preview.text_type=custom&preview.text=Il#standard-styles) and [B612 Mono](https://fonts.google.com/specimen/B612+Mono?query=Il&preview.text_type=custom&preview.text=Il) either of them will work for this project.

**Comment by aquibbaig** [comment]
@StrangeNoob I'd personally prefer the latter i.e. `B612`. If you'll work on it, well and fine, else I'd assign myself

**Comment by StrangeNoob** [comment]
@aquibbaig I will do it

**Comment by aquibbaig** [comment]
@StrangeNoob Progress?

**Comment by moby-dicc** [comment]
@aquibbaig may I work on it?

**Comment by aquibbaig** [comment]
@moby-dicc Go ahead. This is a immediate requirement. So, try to finish this in a day or so
