### ISSUE TITLE
Settings page

### ISSUE THREAD

**Issue by aquibbaig** [zairza-cetb/literature#139]
The appbar looks quite empty and we can add a "settings" icon for developer names, instructions of the game and other stuffs

**Comment by StrangeNoob** [comment]
I would like to work on it. Can you help me what do you need in the setting page?  For Help, We could use `[intro_slider](https://pub.dev/packages/intro_slider)` to get better UI/UX with the game rules.

**Comment by aquibbaig** [comment]
The intro slider can be implemented as a part of "Instructions" to walk people through the various aspects of the game, the settings page is an overall for License agreements, Developer details/ About and Instructions, change theme or game screen layout, restore purchases, etc.

I have added a sample settings screen for reference.
![image](https://user-images.githubusercontent.com/26324376/87394150-f5704f80-c5cc-11ea-8e10-6f63cb74f964.png)

**Comment by StrangeNoob** [comment]
@moby-dicc can you create a smail circular avatar and create a drop down for log out for the user in appbar?

**Comment by moby-dicc** [comment]
I'll be working on it.
