### ISSUE TITLE
Game logic

### ISSUE THREAD

**Issue by aquibbaig** [zairza-cetb/literature#14]
A proper design is needed before we start writing code.

**Comment by aquibbaig** [comment]
![image](https://user-images.githubusercontent.com/26324376/78916324-ef894080-7aaa-11ea-8217-ef7b79f9e5d8.png)

If we could make something like this, it would be great. @amgugu111 @ankitjena ?

**Comment by ani-sha** [comment]
@aquibbaig can use the pop-up feature.

**Comment by amgugu111** [comment]
@aquibbaig this looks good, we can change the background and put animation when you draw a card

**Comment by aquibbaig** [comment]
@amgugu111 We don't draw cards. They are already distributed
