### ISSUE TITLE
Restrict user to join the game using 'join_game' if the user has created the game.

### ISSUE THREAD

**Issue by ganeshpatro321** [zairza-cetb/literature#98]
In the current scenario, a user who has created a game and a roomId. He can go back to the home page and join the game providing the roomId and a different name. This should be restricted.

**Comment by aquibbaig** [comment]
@ganeshpatro321 I think this is already restricted because once user is going back, we are disconnecting him from the socket, hence ending the game. What we could do as a clean up is to remove the room from the server once and for all even if one player disconnects.
